name: void_share
description: A simple file uploader
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  archive: ^3.1.6
  cupertino_icons: ^1.0.2
  dotted_border: ^2.0.0+1
  file_picker: ^4.1.6
  flutter:
    sdk: flutter
  http: ^0.13.4
  loading_indicator: ^3.0.2
  mime: ^1.0.1
  page_transition: ^2.0.4
  path_provider: ^2.0.6
  provider: ^6.0.1
  share_plus: ^3.0.4
  url_launcher: ^6.0.12
  hive: ^2.0.4
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  lint: ^1.7.2
  hive_generator: ^1.1.1
  build_runner: ^2.1.5

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
